from __future__ import annotations

import pytest

from argos.prompts.haiku_judge import (
    HAIKU_JUDGE_SYSTEM_PROMPT,
    HAIKU_JUDGE_SYSTEM_PROMPT1,
    HAIKU_JUDGE_SYSTEM_PROMPT2,
    HAIKU_JUDGE_SYSTEM_PROMPT3,
    HAIKU_JUDGE_SYSTEM_PROMPT4,
    HAIKU_JUDGE_SYSTEM_PROMPT_CLAUDE_HAIKU_4_6,
    HAIKU_JUDGE_SYSTEM_PROMPT_CLAUDE_SONNET_4_6,
    HAIKU_JUDGE_SYSTEM_PROMPT_GEMINI_3_1_FAST,
    HAIKU_JUDGE_SYSTEM_PROMPT_GEMINI_3_1_PRO,
    HAIKU_JUDGE_SYSTEM_PROMPT_GPT_5_3,
)


@pytest.mark.parametrize(
    "system_prompt",
    [
        HAIKU_JUDGE_SYSTEM_PROMPT,
        HAIKU_JUDGE_SYSTEM_PROMPT1,
        HAIKU_JUDGE_SYSTEM_PROMPT2,
        HAIKU_JUDGE_SYSTEM_PROMPT3,
        HAIKU_JUDGE_SYSTEM_PROMPT4,
        HAIKU_JUDGE_SYSTEM_PROMPT_CLAUDE_HAIKU_4_6,
        HAIKU_JUDGE_SYSTEM_PROMPT_CLAUDE_SONNET_4_6,
        HAIKU_JUDGE_SYSTEM_PROMPT_GEMINI_3_1_FAST,
        HAIKU_JUDGE_SYSTEM_PROMPT_GEMINI_3_1_PRO,
        HAIKU_JUDGE_SYSTEM_PROMPT_GPT_5_3,
    ],
)
def test_system_prompt(system_prompt: str) -> None:
    assert isinstance(system_prompt, str)
